[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
crypnight_contracts = "DKoawaEk5pJj1npwNYXeCCPF3Uqzxahokq67NY387qbK"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
