[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
crypnight_contracts = "8X3ZpcDBiQ2ZkRbWpVk8rNmAgpZk862KsdP4sQsjjG9x"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
