[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
crypnight_contracts = "F1E8QvpUYJP71zWz4NwYpPtpUszfp8wb2nKjnrzF2Cmh"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
